### ISSUE TITLE
pyproject.toml specifies repository as safe-assert

### ISSUE THREAD

**Issue by sethwoodworth** [wemake-services/wemake-python-package#1]
https://github.com/wemake-services/wemake-python-package/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L20
```
repository = "https://github.com/sobolevn/safe-assert"
```
This should be a cookiecutter variable or unset.

**Comment by sobolevn** [comment]
Oops, thanks!

**Comment by sobolevn** [comment]
@sethwoodworth congrats on the first issue on this project 🎉 

It is fixed now.
