### ISSUE TITLE
easy update process

### ISSUE THREAD

**Issue by johnbomidi** [wemake-services/wemake-python-package#148]
"Easy update process, so your template will always be up-to-date" is listed as a feature.  I interpret that as if you made a project with this template, you can update the project to the latest template? Is that true, if so it is not clear how one goes about doing that.

**Comment by sobolevn** [comment]
Hi, @johnbomidi! 

You can see what has changed since your project was generated: https://github.com/wemake-services/wemake-python-package/tree/master/%7B%7Bcookiecutter.project_name%7D%7D#credits

To achieve this we include a diff link to all projects we generate. This will help you to update.
