### ISSUE TITLE
Consider to make the ./docs/Makefile targets available in ./Makefile

### ISSUE THREAD

**Issue by cruisen** [wemake-services/wemake-python-package#77]
Consider to make the ./docs/Makefile targets available in ./Makefile. For example like this:
```Make

.PHONY: html
html:
        cd docs && $(MAKE) html
```
---
However I have not figured out a way to make all ./docs/Makefile targets available without to much boilerplate ;-(
That did not help either: "Managing Large Projects" with make: https://www.oreilly.com/library/view/managing-projects-with/0596006101/ch06.html

**Comment by sobolevn** [comment]
PRs are welcome!

**Comment by cruisen** [comment]
Added https://github.com/wemake-services/wemake-python-package/pull/345
